/almac/ignacio/data/INEXQA2012corpus/wikiEn_sts_clean_ph2_tfidf-binary-ost.pk
/almac/ignacio/data/INEXQA2012corpus/wikiEn_sts_clean_ph2_tfidf-binary-wst.pk
/almac/ignacio/data/INEXQA2012corpus/wikiEn_sts_clean_ph2_tfidf-freq-ost.pk
/almac/ignacio/data/INEXQA2012corpus/wikiEn_sts_clean_ph2_tfidf-freq-wst.pk
/almac/ignacio/data/INEXQA2012corpus/wikiEn_sts_clean_ph2_tfidf-sublinear-ost.pk
/almac/ignacio/data/INEXQA2012corpus/wikiEn_sts_clean_ph2_tfidf-sublinear-wst.pk
