/almac/ignacio/data/sts/sts2016-english-with-gs-v1.0/STS2016.input.answer-answer.txt
/almac/ignacio/data/sts/sts2016-english-with-gs-v1.0/STS2016.input.headlines.txt
/almac/ignacio/data/sts/sts2016-english-with-gs-v1.0/STS2016.input.plagiarism.txt
/almac/ignacio/data/sts/sts2016-english-with-gs-v1.0/STS2016.input.postediting.txt
/almac/ignacio/data/sts/sts2016-english-with-gs-v1.0/STS2016.input.question-question.txt
